### ISSUE TITLE
JUSTIFICATION_MODE_NONE does not exist on Android API level 25

### ISSUE THREAD

**Issue by jarmani** [nativescript-community/ui-label#11]
### Which platform(s) does your issue occur on?
Android 7.1.X (API level 25)

### Please, tell us how to recreate the issue in as much detail as possible.
JUSTIFICATION_MODE_INTER_WORD and JUSTIFICATION_MODE_NONE appeared in [API level 26 ](https://developer.android.com/reference/android/text/Layout#JUSTIFICATION_MODE_NONE) but the code [check for level >= 25](https://github.com/nativescript-community/ui-label/blob/9a124d1823a131d3a2cf1753a661b6984b562b7f/src/label.android.ts#L429) :

```typescript
[textAlignmentProperty.setNative](value: CoreTypes.TextAlignmentType) {
        const view = this.nativeTextViewProtected;
        if (android.os.Build.VERSION.SDK_INT >= 25) {
            if ((value as any) === 'justify') {
                view.setJustificationMode(android.text.Layout.JUSTIFICATION_MODE_INTER_WORD);
            } else {
                view.setJustificationMode(android.text.Layout.JUSTIFICATION_MODE_NONE);
                view.setGravity(getHorizontalGravity(value) | getVerticalGravity(this.verticalTextAlignment));
            }
        } else {
            view.setGravity(getHorizontalGravity(value) | getVerticalGravity(this.verticalTextAlignment));
        }
    }
```

causing the following error :

`com.tns.NativeScriptException: Calling js method onCreateView failed
Error: java.lang.NoSuchFieldError: no "I" field "JUSTIFICATION_MODE_NONE" in class "Landroid/text/Layout;" or its superclasses`

**Comment by farfromrefug** [comment]
@jarmani thanks for the report. fixed in 1.2.2
