### ISSUE TITLE
Bug: cannot read property 'spans' of undefined on link tap

### ISSUE THREAD

**Issue by bradmartin** [nativescript-community/ui-label#16]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS
- iOS/Android versions  - 16.1 (only tested so far)
- emulator or device. What type of device? emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/@nativescript/core/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

```bash
MacBook-Pro:nativescript-byram bradmartin$ ns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.4.0 version and is up to date.
✔ Component @nativescript/core has 8.4.4 version and is up to date.
✔ Component @nativescript/ios has 8.4.0 version and is up to date.
✔ Component @nativescript/android has 8.4.0 version and is up to date.
```

```json
    "@nativescript-community/ui-label": "~1.2.16",
     "@nativescript/ios": "~8.4.0",
    "@nativescript/types": "~8.4.0",
    "@nativescript/webpack": "~5.0.12",
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 

```html
 <HTMLLabel
      class="p-y-10 m-b-5"
      fontSize="14"
      fontWeight="normal"
      linkColor="#336699"
      linkUnderline="true"
      [html]="orderConfirmationMessage"
      (linkTap)="onConfirmationLinkTap($event)"
      textWrap="true"
    ></HTMLLabel>
```

```html
"<p>Your order has been received. You will receive an order confirmation number when your order is in process. Please allow 1 – 2 business days for verifying your insurance coverage & authorizations. If more information is needed, we will contact you.</p> <br/> <p>Once your order ships, you will receive a shipping confirmation with tracking details. To check your order status at any time, view your <a href='https://order_history.com'>Order History.</a></p>"
```

Can't seem to figure out "when" this started. In this project things were fine a couple months ago with releases. I think the implementation is fine. Just unsure why this happens on the iOS "tap" of the link. I've tried a few different html tags for input but no luck yet.

**Comment by farfromrefug** [comment]
@bradmartin sorry will fix this right away

**Comment by bradmartin** [comment]
No rush, I poked around at the source but nothing jumped out to me as to why this was throwing where it did. Thanks though 👍🏻

**Comment by bradmartin** [comment]
Confirmed. Thanks

**Comment by bradmartin** [comment]
i pulled the source here and packed it, already in production. Wasn't sure you were waiting to do the npm release or what  😁

**Comment by farfromrefug** [comment]
@bradmartin oh ok sorry about that !
