### ISSUE TITLE
[1.3.5][Android] linkColor crashes the app

### ISSUE THREAD

**Issue by MrSnoozles** [nativescript-community/ui-label#17]
After updating from `1.2.26` to `1.3.5` when I use the linkColor attribute the app now crashes.

~~~vue
<HTMLLabel :html="getDisclaimerText()"
                   @linkTap="openStorePage"
                   linkColor="#9ca3af"
                   :textWrap="true"
                   :lineHeight="18"
                   class="border-t mt-6 p-3 text-sm text-gray-400"></HTMLLabel>
~~~

![grafik](https://github.com/nativescript-community/ui-label/assets/17496592/b474c87f-f7c5-48e1-8d43-1964b7d33e62)

**Comment by nikoTM** [comment]
@farfromrefug https://github.com/nikoTM/ns-linkColor running that on API 25 crashes

**Comment by nikoTM** [comment]
https://developer.android.com/reference/android/graphics/Color#valueOf(int)

It looks like `valueOf(int)` was added in `API 26` and this [createNativeAttributedString](https://github.com/nativescript-community/text/blob/0cf16bfa047e15879e49ea1e3e22fb0ac57c924e/src/text/index.android.ts#L218) uses that API.

Color spaces were introduced in Android O (https://stackoverflow.com/questions/60083126/create-color-object-from-rgb-values-for-api-level-android-26-oreo), not sure how to convert a hex to Color instance pre API 25

**Comment by farfromrefug** [comment]
@nikoTM @MrSnoozles i just released a new version which fixes this
